import { hydrateGovernance, actor, executeOwnedAction } from '../core/governed-actions.js';
import { head, kpis, esc, badge, toast } from '../core/ui.js';
import { UIState } from '../core/ui-state.js';
import { Entities } from '../core/entity-store.js';
import { ArchiveService } from '../core/archive.js';
import { State } from '../core/state.js';
export async function mount(el){hydrateGovernance();render(el);}
function currentActor(){ return State.get().profile || actor(); }
function rows(){ const s=Entities.snapshot(); return (s.byRef||[]).map(([ref,b])=>({ref,open:Entities.canClose(ref),archived:!!Entities.getArchive(ref)})); }
function render(el){ const stats=Entities.stats(); const u=UIState.get('archive',{queue:'All'}); const list=rows().filter(r=>u.queue==='All'||(u.queue==='Ready'&&r.open.ok&&!r.archived)||(u.queue==='Blocked'&&!r.open.ok&&!r.archived)||(u.queue==='Archived'&&r.archived)); el.innerHTML=`<div class="workspace">${head('Archive Evidence','Immutable reference bundles, audit threads, retention evidence and reopen controls.')}${kpis([['Archived',stats.archives],['References',stats.references],['Quarantine',stats.quarantine],['Ready to close',rows().filter(r=>r.open.ok&&!r.archived).length]])}<div class="toolbar"><span class="meta">Archive owns immutable closure evidence; search and retrieval stay in Lookup.</span><select data-queue aria-label="Filter closure readiness">${['All','Ready','Blocked','Archived'].map(x=>`<option ${x===u.queue?'selected':''}>${x}</option>`).join('')}</select><button class="btn ghost" data-refresh>Refresh</button></div><div class="split"><section class="panel"><div class="eyebrow panel-eyebrow">Archive Controls</div><form id="archive-form" class="grid"><label>Reference<input name="ref" required placeholder="REF-..." /></label><label class="wide">Closure Summary<textarea name="summary" rows="3">Closed and ready for archive.</textarea></label><div class="wide"><button class="btn" data-archive>Archive Reference</button></div></form></section><section class="panel detail-col"><div class="eyebrow panel-eyebrow">Reference Closure Readiness</div><div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Reference</th><th>Can Close</th><th>Archived</th><th>Actions</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(r.ref)}</td><td>${badge(r.open.ok?'Ready':'Blocked',r.open.ok?'ok':'warn')}</td><td>${badge(r.archived?'Archived':'Active',r.archived?'ok':'')}</td><td><button class="btn ghost compact" data-ref="${esc(r.ref)}">Inspect</button></td></tr>`).join('')||'<tr><td colspan="4">No references in this queue.</td></tr>'}</tbody></table></div></section></div></div>`; el.querySelector('[data-queue]').onchange=e=>{UIState.set('archive',{queue:e.target.value});render(el);}; el.querySelector('#archive-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await executeOwnedAction('archive','archive-reference',()=>ArchiveService.archiveReference(d.ref,currentActor(),{closureSummary:d.summary}),{ref:d.ref});toast('Archived '+d.ref,'success');render(el);}catch(err){toast(err.message||'Archive failed','error');}}; el.querySelector('[data-refresh]').onclick=()=>render(el); el.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>{const f=el.querySelector('#archive-form');f.ref.value=b.dataset.ref;f.ref.focus();}); }
export async function archiveReference(ref, closureSummary='Closed and ready for archive'){ return ArchiveService.archiveReference(ref,currentActor(),{closureSummary}); }
