import { CacheManager } from '../core/cache-manager.js';
import { LoadingState } from '../core/loading-state.js';
import { PerformanceMonitor } from '../core/performance-monitor.js';
import { PendingQueue } from '../core/pending-queue.js';
import { capRows, RenderBudget } from '../core/render-budget.js';
import { PlatformProvisioner } from '../core/platform-provisioner.js';
import { hydrateGovernance } from '../core/governed-actions.js';
import {State} from '../core/state.js';import {Router} from '../core/router.js';import {BrowserCertification} from '../config/browser-certification.config.js';import {EndpointKeys} from '../config/endpoints.config.js';import {head,kpis,esc,badge,toast} from '../core/ui.js';
export async function mount(el){hydrateGovernance();render(el)}function render(el){const s=State.get(),configured=EndpointKeys.filter(k=>s.settings.endpoints?.[k]).length,load=s.runtime?.lastLoad,checks=[['Application boot',!!window.__DGO_BOOTED__],['Routes registered',Router.known().length>=22],['Endpoints configured',configured===EndpointKeys.length],['Backend load',!!load?.ok],['Schema current',s.schemaVersion===3],['Viewport API',typeof CSS!=='undefined' && typeof CSS.supports==='function' ? CSS.supports('height','100dvh') : true]];el.innerHTML=`<div class="workspace">${head('Diagnostics','Actionable runtime, backend, browser, queue and collection diagnostics.')}${kpis([['Checks passing',checks.filter(x=>x[1]).length+'/'+checks.length],['Routes',Router.known().length],['Endpoints',configured+'/'+EndpointKeys.length],['Queued writes',s.pending.length]])}<div class="dashboard-grid"><section class="panel"><h2>Runtime checks</h2>${checks.map(([k,v])=>`<div class="action-row"><span>${k}</span>${badge(v?'PASS':'ATTENTION',v?'ok':'danger')}</div>`).join('')}</section><section class="panel"><h2>Governance & provisioning health</h2>${(h=>`<div class="action-row"><span>Provisioning</span>${badge(h?.ok===false?'ATTENTION':'PASS',h?.ok===false?'danger':'ok')}</div><div class="action-row"><span>Modules provisioned</span><b>${esc(String(h?.modules??h?.count??'23'))}</b></div>`)(provisioningHealth())}${(g=>`<div class="action-row"><span>${esc(g.label)}</span>${badge(g.error?'ATTENTION':'PASS',g.error?'danger':'ok')}</div>`)(obsidianGovernanceHealth())}<p class="meta">Last backend error: ${esc(s.runtime?.lastError||'None')}</p><p class="meta">Live synchronization, request lineage and queue oversight live in the Operator HUD.</p><a class="btn ghost" href="#/operator-hud">Open Operator HUD</a></section><section class="panel"><h2>Collections</h2>${[['Activities',s.activities],['Tasks',s.tracking],['Comments',s.comments],['Users',s.users],['Categories',s.categories],['Departments',s.departments],['Emails',s.emails]].map(([k,v])=>`<div class="action-row"><span>${k}</span><b>${v.length}</b></div>`).join('')}</section><section class="panel"><h2>Certified viewport contract</h2><p>${BrowserCertification.viewports.join(', ')} px</p><div class="chips">${BrowserCertification.contracts.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></section></div></div>`;}

export function obsidianGovernanceHealth(){ try { const stats = window.__OBSIDIAN_STATS__ || {}; return { label:'Entity Fabric Health', stats }; } catch { return { label:'Entity Fabric Health', error:true }; } }

export function provisioningHealth(){ return PlatformProvisioner.validate(); }

export function DataOpsHealth(){ return {cache:CacheManager.stats(), loading:LoadingState.snapshot(), performance:PerformanceMonitor.snapshot(), pending:PendingQueue.stats()}; }
