import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { head, kpis, esc, badge, toast, confirmAction, mdBack, mdSwitch, resetDetailScroll,fmtDate,fmtDateTime} from '../core/ui.js';
import { status, statusTone } from '../core/domain.js';
import { setCorrespondenceStatus, createTask, enrichCorrespondence } from '../core/enterprise-domain.js';
import { priorityOptions, priorityLabel, priorityTone, normalizePriority } from '../config/priority.config.js';
import { requestSync } from '../core/data-loader.js';
import { exportJson } from '../core/report-export-service.js';
import { invoke } from '../core/api.js';
import { UIState } from '../core/ui-state.js';
let selectedId='', mdView='list';
function syncLocal(){const u=UIState.get('executive',{selected:'',md:'list'});selectedId=u.selected;mdView=u.md;}
function corrRows(s){return (s.correspondence?.length?s.correspondence:s.activities.map(a=>enrichCorrespondence(a))).map(c=>({...c,_tasks:relatedTasks(c,s),_emails:relatedEmails(c,s)}));}
import { relatedTasks, relatedEmails } from '../core/data-selectors.js';
function role(email){email=String(email||'').toLowerCase();return email.includes('dg@')?'DGCEO':(email.includes('dgs')||email.includes('registry'))?'EA':'Officer';}
const stateClass=x=>statusTone(x);
export async function mount(el){hydrateGovernance();render(el);}
function render(el){syncLocal();const s=State.get(),r=role(s.profile.email),rows=corrRows(s).sort((a,b)=>new Date(b.receivedAt||0)-new Date(a.receivedAt||0)),over=s.tracking.filter(t=>t.due&&new Date(t.due)<new Date()&&t.status!=='Completed'),awaiting=rows.filter(c=>!/accepted|approved|closed|archived/i.test(c.status||'')),item=rows.find(x=>String(x.id)===String(selectedId))||rows[0];if(!selectedId&&item){selectedId=item.id;UIState.set('executive',{selected:item.id});}el.innerHTML=`<div class="workspace role-${r}">${head('DGCEO Correspondence & Decision Hub','Executive dashboard, polymorphic matrix, decision authority, quick minutes and EA routing.')}${kpis([['Overdue',over.length],['Awaiting Decision',awaiting.length],['On Track',rows.length-awaiting.length],['Role',r]])}<div class="toolbar"><button class="btn" data-sync-live>Sync Live Data</button><button class="btn ghost" data-switch-role>Switch user / role</button><a class="btn ghost" href="#/correspondence">Open Tracker</a></div><div class="dg-layout" ${mdSwitch(item?mdView:'list')}><section class="panel panel-inbox"><h2>Executive Dashboard</h2><div class="dashboard-metrics"><span class="tag overdue">Overdue: ${over.length}</span><span class="tag awaiting">Awaiting Decision: ${awaiting.length}</span><span class="tag ok">On Track: ${rows.length-awaiting.length}</span></div><h2>Incoming Correspondences</h2><div class="list-col">${rows.map(c=>`<article class="list-item ${String(c.id)===String(selectedId)?'active':''}" data-exec-select="${esc(c.id)}"><span class="doc-list-title">${esc(c.subject)}</span><div class="meta">${esc(c.referenceId||c.id||'—')} · ${badge(c.status||'Pending',stateClass(c.status||''))} · ${esc(fmtDate(c.receivedAt||''))}</div></article>`).join('')||'<div class="empty">Click Sync Live Data to fetch flows.</div>'}</div></section><div class="detail-col panel-stack" id="panel-details">${item?detail(item,s,r):'<section class="panel"><div class="empty"><h2>Select an item</h2></div></section>'}</div><section class="panel panel-actions dg-only"><h2>DGCEO Decision</h2><button class="btn" data-exec-approve>Approve / Accept</button><button class="btn danger" data-exec-return>Decline / Reject</button><button class="btn ghost" data-exec-escalate>Delegate via EA</button><hr><h2>Quick Minute</h2><textarea data-minute rows="4" placeholder="Type your directive here..."></textarea><button class="btn" data-append-minute>Append to Document</button><button class="btn ghost" data-export-decision>Export Decision</button></section></div></div>`;wire(el,item,s,r);}
function detail(c,s,r){return `${mdBack('Back to inbox')}<section class="panel"><h2>Correspondence Details</h2><h3>${esc(c.subject)}</h3><div class="status-strip">${badge(c.status||'Pending',stateClass(c.status||''))} ${badge(c.category||'Unclassified')} ${badge(priorityLabel(c.priority),priorityTone(c.priority))}</div><dl class="detail-grid"><dt>Reference</dt><dd>${esc(c.referenceId||c.id||'—')}</dd><dt>Sender</dt><dd>${esc(c.sender||'Not recorded')}</dd><dt>Received</dt><dd>${esc(fmtDateTime(c.receivedAt||''))}</dd><dt>Assigned</dt><dd>${esc(c.assignedTo||'Unassigned')}</dd></dl>${c.attachmentLink?`<a class="btn ghost" href="${esc(c.attachmentLink)}" target="_blank" rel="noreferrer">Open Original Document</a>`:''}</section><section class="ai-preview"><h2>AI Classification Preview</h2><p><b>Suggested Category:</b> ${esc(c.category||'Unclassified / Governance')}</p><p><b>Suggested Priority:</b> ${esc(priorityLabel(c.priority||'high'))}</p><button class="btn ghost" data-apply-ai>Apply Suggestions to Metadata</button></section><section class="panel"><h2>Linked Execution Tasks (${c._tasks.length})</h2>${c._tasks.map(t=>`<div class="matrix-card"><h4>${esc(t.title)}</h4><div class="matrix-meta"><b>RefID:</b> ${esc(t.referenceId||t.RefIDD||'—')}</div><div class="matrix-meta"><b>Status:</b> ${esc(t.status||'Pending')} · <b>Assigned:</b> ${esc(t.assignedTo||'—')}</div></div>`).join('')||'<p class="meta">No tasks spawned from this lineage.</p>'}</section><section class="panel"><h2>Communication Threads (${c._emails.length})</h2>${c._emails.map(e=>`<div class="matrix-card"><h4>${esc(e.subject)}</h4><div class="matrix-meta"><b>From:</b> ${esc(e.fromName||e.fromAddress||'—')} · <b>Date:</b> ${esc(fmtDateTime(e.receivedDateTime||''))}</div><p>${esc(e.bodyPreview||'')}</p></div>`).join('')||'<p class="meta">No correlated emails detected.</p>'}</section><section class="panel"><h2>Matrix Audit Trail</h2><ul class="timeline"><li><b>${esc(fmtDate(c.receivedAt||'')||'N/A')}</b> - Document ingested into Data Model.</li><li><b>Status:</b> ${esc(c.status||'Pending')}</li>${c.assignedTo?`<li><b>Routed To:</b> ${esc(c.assignedTo)}</li>`:''}</ul></section><section class="panel ea-only"><h2>Route / Assign Task</h2><select data-route-dept><option value="">Select Department DSU...</option>${s.departments.map(d=>`<option value="${esc(d.dsuKey||d.DSU_KEY||d.title)}">${esc(d.title||d.Title)} (${esc(d.dsuKey||d.DSU_KEY||'')})</option>`).join('')}</select><select data-route-assignee><option value="">Select User / Assignee...</option>${s.users.map(u=>`<option value="${esc(u.email)}">${esc(u.fullName||u.name||u.email)}</option>`).join('')}</select><select data-route-priority>${priorityOptions('normal')}</select><textarea data-route-notes rows="3" placeholder="Routing instructions & minute notes..."></textarea><button class="btn" data-route-task>Create & Route Task</button></section>`;}
function wire(el,item,s,r){el.querySelectorAll('[data-exec-select]').forEach(b=>b.onclick=()=>{UIState.set('executive',{selected:b.dataset.execSelect,md:'detail'});render(el);resetDetailScroll(el)});el.querySelector('[data-md-back]')?.addEventListener('click',()=>{UIState.set('executive',{md:'list'});render(el)});el.querySelector('[data-sync-live]')?.addEventListener('click',syncLive);el.querySelector('[data-switch-role]')?.addEventListener('click',()=>toast('Switch role via Settings profile email. Current role: '+r,'info'));if(!item)return;const ref=item.referenceId||item.id||'';const update=async(action,label,patch)=>{if(!await confirmAction({title:label,body:`<p>${esc(item.subject||item.title||item.id)}</p><pre class="preview-box">${esc(JSON.stringify({reference:ref,action,label},null,2))}</pre>`}))return;await executeOwnedAction('executive',action,()=>{patch();State.patch({correspondence:s.correspondence,tracking:s.tracking,approvals:s.approvals,comments:s.comments,audit:s.audit},{module:'executive',action,ref});toast(label,'success');render(el);},{ref});};const decide=(action,label,status)=>update(action,label,()=>{const res=setCorrespondenceStatus(s,item.id,status,s.profile.email,{surface:'executive'});if(res){s.correspondence=res.patch.correspondence;s.audit=res.patch.audit;}});el.querySelector('[data-exec-approve]')?.addEventListener('click',()=>decide('executive-approve','Executive approval recorded','Accepted'));el.querySelector('[data-exec-return]')?.addEventListener('click',()=>decide('executive-return','Declined / rejected by DGCEO','Declined'));el.querySelector('[data-exec-escalate]')?.addEventListener('click',()=>decide('executive-escalate','Delegated via EA','Delegated'));el.querySelector('[data-append-minute]')?.addEventListener('click',()=>appendMinute(el,item,s));el.querySelector('[data-route-task]')?.addEventListener('click',()=>routeTask(el,item,s));el.querySelector('[data-apply-ai]')?.addEventListener('click',()=>toast('AI classification suggestions applied to local metadata preview','success'));el.querySelector('[data-export-decision]')?.addEventListener('click',()=>exportJson('executive-decision.json',{at:new Date().toISOString(),item,actor:s.profile}));}
async function appendMinute(el,item,s){const note=el.querySelector('[data-minute]')?.value||'';if(!note.trim())return toast('Enter a quick minute first','error');if(!await confirmAction({title:'Append quick minute',body:`<p>${esc(item.subject)}</p><pre class="preview-box">${esc(note)}</pre>`}))return;await executeOwnedAction('executive','append-minute',()=>{State.patch({comments:[{id:crypto.randomUUID(),referenceId:item.referenceId||item.id,body:note,author:s.profile.email,ts:new Date().toISOString(),type:'executive-minute'},...s.comments]},{module:'executive',action:'append-minute',ref:item.referenceId||item.id});},{ref:item.referenceId||item.id});invoke('DYNAMIC_ACTIONS',{action:'appendMinute',ref:item.referenceId||item.id,note}).catch(()=>toast('Minute saved locally; sync queued','error'));toast('Minute appended','success');render(el);}
async function routeTask(el,item,s){const assignee=el.querySelector('[data-route-assignee]')?.value,dept=el.querySelector('[data-route-dept]')?.value,priority=el.querySelector('[data-route-priority]')?.value,notes=el.querySelector('[data-route-notes]')?.value;if(!assignee)return toast('Select an assignee','error');const r=createTask(s,{title:item.subject,referenceId:item.referenceId||item.id,assignedTo:assignee,assignedToDsu:dept,priority,description:notes},s.profile.email,{surface:'executive'});if(!await confirmAction({title:'Create & Route Task',body:`<p>${esc(item.subject)}</p><pre class="preview-box">${esc(JSON.stringify(r.task,null,2))}</pre>`}))return;await executeOwnedAction('executive','route-task',()=>{State.patch(r.patch,{module:'executive',action:'route-task',ref:r.task.referenceId});invoke('SINGLE_ASSIGNMENT',{activity:item,tracking:r.task}).catch(()=>toast('Task saved locally; sync queued','error'));},{ref:r.task.referenceId});toast('Task routed','success');render(el);}
async function syncLive(){if(!await confirmAction({title:'Sync Live Data',body:'Fetch Documents, Tasks, Emails and Lookups through the governed platform data client?',confirmText:'Sync Live Data',cancelText:'Cancel'}))return;try{await requestSync({source:'executive',mode:'full'});toast('Live data sync requested','success')}catch{toast('Sync unavailable; local state remains active','error')}}
