import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { head, kpis, esc, badge, toast, confirmAction } from '../core/ui.js';
import { invoke } from '../core/api.js';
import { UIState } from '../core/ui-state.js';
let trace=[];
function risk(t,now=Date.now()){const due=t.due?new Date(t.due).getTime():null;return t.status==='Completed'?'Complete':!t.assignedTo?'Unassigned':due&&due<now?'Breached':due&&due-now<=86400000?'Due soon':(t.priority||'normal');}
function emailsFor(doc,s){return (s.emails||[]).filter(e=>{const t=String(doc.title||'').toLowerCase();return t&&(`${e.subject||''} ${e.bodyPreview||''} ${e.bodyContent||''}`.toLowerCase().includes(t));});}
function pairs(s){return s.activities.flatMap(a=>emailsFor(a,s).map(e=>({doc:a,email:e})));}
function matrix(s){return s.activities.map(a=>({doc:a,tasks:s.tracking.filter(t=>String(t.referenceId||'')===String(a.referenceId||a.id)),emails:emailsFor(a,s)}));}
function log(action,status,message,duration=0){trace.unshift({at:new Date().toISOString(),action,status,message,duration});trace=trace.slice(0,80);}
function ribbon(){return `<div class="action-ribbon"><button class="btn ghost" data-action="FETCH_ALL">Reload All</button><button class="btn ghost" data-action="GET_DOCS">Docs</button><button class="btn ghost" data-action="FETCH_ACTIVITIES">Tasks</button><button class="btn ghost" data-action="SUBSIDIARY_ACTIONS">Emails</button><button class="btn ghost" data-recalc>Dashboard</button><button class="btn ghost" data-action="REFERENCE_DATA">References</button></div>`;}
function renderQueue(tasks){return `<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Reference</th><th>Task</th><th>Owner</th><th>Due</th><th>Risk</th><th>Actions</th></tr></thead><tbody>${tasks.sort((a,b)=>a._due-b._due).slice(0,120).map(t=>`<tr><td>${esc(t.referenceId||'—')}</td><td>${esc(t.title)}</td><td>${esc(t.assignedTo||'Unassigned')}</td><td>${esc(t.due?String(t.due).slice(0,10):'Not set')}</td><td>${badge(t._risk,t._risk==='Breached'||t._risk==='Unassigned'?'danger':t._risk==='Complete'?'ok':'warn')}</td><td><button class="btn ghost" data-fasttrack="${esc(t.id)}">FastTrack</button><button class="btn ghost" data-escalate="${esc(t.id)}">Escalate</button><button class="btn ghost" data-notify="${esc(t.id)}">Notify</button></td></tr>`).join('')}</tbody></table></div>`;}
function renderMatched(s){const rows=s.activities.filter(a=>emailsFor(a,s).length);return `<div class="list-col">${rows.map(a=>`<article class="list-item"><h4>${esc(a.title)}</h4><div class="meta">${esc(a.referenceId||'—')} · ${emailsFor(a,s).length} matching email(s) · ${esc(a.category||'Unclassified')}</div></article>`).join('')||'<div class="empty">No matched documents.</div>'}</div>`;}
function renderPairs(s){const ps=pairs(s);return `<div class="list-col">${ps.map(p=>`<article class="list-item"><h4>${esc(p.doc.title)}</h4><div class="meta">↳ ${esc(p.email.subject||'No subject')} · ${esc(p.email.fromAddress||p.email.from||'—')}</div></article>`).join('')||'<div class="empty">No document-email pairs.</div>'}</div>`;}
function renderMatrix(s){const mx=matrix(s);return `<div class="list-col">${mx.map(m=>`<article class="list-item"><h4>${esc(m.doc.title)}</h4><div class="meta">Tasks: ${m.tasks.length} · Emails: ${m.emails.length} · Reference: ${esc(m.doc.referenceId||m.doc.id)}</div></article>`).join('')||'<div class="empty">No matrix data.</div>'}</div>`;}
function renderTelemetry(){return `<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Timestamp</th><th>Action</th><th>Status</th><th>Duration</th><th>Message</th></tr></thead><tbody>${trace.map(t=>`<tr><td>${esc(t.at.slice(11,19))}</td><td>${esc(t.action)}</td><td>${esc(t.status)}</td><td>${esc(t.duration)}ms</td><td>${esc(t.message)}</td></tr>`).join('')||'<tr><td colspan="5">No telemetry yet. Run an action to populate metrics.</td></tr>'}</tbody></table></div>`;}
export async function mount(el){hydrateGovernance();render(el);}
function render(el){const {view}=UIState.get('fasttrack',{view:'queue'});const s=State.get(),now=Date.now(),tasks=s.tracking.map(t=>({...t,_risk:risk(t,now),_due:t.due?new Date(t.due).getTime():Infinity}));const breached=tasks.filter(t=>t._risk==='Breached'),due=tasks.filter(t=>t._risk==='Due soon'),unowned=tasks.filter(t=>t._risk==='Unassigned');el.innerHTML=`<div class="workspace">${head('FastTrack Web Ops','Priority intervention queue plus matched docs, doc-email pairs, response matrix and action telemetry.')}${kpis([['Breached',breached.length],['Due within 24h',due.length],['Unassigned',unowned.length],['Tracked',tasks.length]])}${ribbon()}<div class="toolbar"><span class="meta">FastTrack owns urgent assignment, escalation and notification actions.</span><button class="chip ${view==='queue'?'active':''}" data-view="queue">Queue</button><button class="chip ${view==='matched'?'active':''}" data-view="matched">Matched Docs</button><button class="chip ${view==='pairs'?'active':''}" data-view="pairs">Doc-Email Pairs</button><button class="chip ${view==='matrix'?'active':''}" data-view="matrix">Response Matrix</button><button class="chip ${view==='telemetry'?'active':''}" data-view="telemetry">Telemetry</button><a class="btn ghost" href="#/orchestrator">Open Orchestrator</a></div><section class="panel">${view==='queue'?renderQueue(tasks):view==='matched'?renderMatched(s):view==='pairs'?renderPairs(s):view==='matrix'?renderMatrix(s):renderTelemetry()}</section></div>`;wire(el);}
function wire(el){const s=State.get();el.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{UIState.set('fasttrack',{view:b.dataset.view});render(el)});el.querySelector('[data-recalc]').onclick=()=>{log('Dashboard','Success',`Matched ${pairs(State.get()).length} doc-email pair(s)`);UIState.set('fasttrack',{view:'telemetry'});render(el)};el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>fetchAction(b.dataset.action));const act=async(id,action,label,make)=>{const t=s.tracking.find(x=>x.id===id);if(!t)return;if(!await confirmAction({title:label,body:`<p>${esc(t.title)}</p>`}))return;await executeOwnedAction('fasttrack',action,()=>{State.patch(make(t),{module:'fasttrack',action,ref:t.referenceId||''});log(action,'Success',t.title);toast(label,'success');render(el);},{ref:t.referenceId||''});};el.querySelectorAll('[data-fasttrack]').forEach(b=>b.onclick=()=>act(b.dataset.fasttrack,'fasttrack','FastTrack applied',t=>({tracking:s.tracking.map(x=>x.id===t.id?{...x,fastTracked:true,priority:'P1'}:x)})));el.querySelectorAll('[data-escalate]').forEach(b=>b.onclick=()=>act(b.dataset.escalate,'escalate-priority','Escalated priority',t=>({tracking:s.tracking.map(x=>x.id===t.id?{...x,escalationLevel:'sla',priority:'P1'}:x)})));el.querySelectorAll('[data-notify]').forEach(b=>b.onclick=()=>act(b.dataset.notify,'notify-owner','Owner notification queued',t=>({notifications:[{id:crypto.randomUUID(),at:new Date().toISOString(),referenceId:t.referenceId,title:`FastTrack notice: ${t.title}`,assignedTo:t.assignedTo||''},...s.notifications]})));}
async function fetchAction(key){const start=performance.now();if(!await confirmAction({title:'Confirm FastTrack data action',body:`<p>Run governed ${esc(key)} request?</p><pre class="preview-box">${esc(JSON.stringify({endpoint:key,source:'DGO_FAST_Track_WEB_OPS'},null,2))}</pre>`,confirmText:'Run action',cancelText:'Cancel'}))return;try{await invoke(key,{operation:'read',mode:'read',source:'DGO_FAST_Track_WEB_OPS'});log(key,'Success','Request completed',Math.round(performance.now()-start));toast('FastTrack action completed','success')}catch(e){log(key,'Error',e.message||'Request failed',Math.round(performance.now()-start));toast('Endpoint unavailable; telemetry recorded','error')}UIState.set('fasttrack',{view:'telemetry'});}
