import { hydrateGovernance } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { status, makeRef } from '../core/domain.js';
import { head, esc, chips, badge, toast, confirmAction } from '../core/ui.js';
import { invoke } from '../core/api.js';
import { UIState } from '../core/ui-state.js';
const U=()=>UIState.get('lookup',{q:'',scope:'all',selType:'',selId:''});
let q='', scope='all', selected={type:'',id:''};
function syncLocal(){const u=U();q=u.q;scope=u.scope;selected={type:u.selType,id:u.selId};}
const SCOPES=[{value:'all',label:'All'},{value:'activities',label:'Activities'},{value:'tasks',label:'Tasks'},{value:'emails',label:'Emails'},{value:'comments',label:'Comments'},{value:'approvals',label:'Approvals'}];
const ROUTE={activities:'activities',tasks:'orchestrator',comments:'comments',approvals:'approvals'};
const vec=v=>String(v||'').toLowerCase();
const hit=(...xs)=>!q||xs.some(x=>vec(x).includes(vec(q)));
function groups(s){const out={};if(scope==='all'||scope==='activities'){const rows=s.activities.filter(a=>hit(a.title,a.referenceId,status(a),a.category,a.assignedTo));if(rows.length)out.activities=rows}if(scope==='all'||scope==='tasks'){const rows=s.tracking.filter(t=>hit(t.title,t.referenceId,t.assignedTo,t.status,t.priority));if(rows.length)out.tasks=rows}if(scope==='all'||scope==='emails'){const rows=(s.emails||[]).filter(e=>hit(e.subject,e.bodyPreview,e.fromAddress,e.from));if(rows.length)out.emails=rows}if(scope==='all'||scope==='comments'){const rows=s.comments.filter(c=>hit(c.body,c.author,c.referenceId));if(rows.length)out.comments=rows}if(scope==='all'||scope==='approvals'){const rows=s.approvals.filter(a=>hit(a.title,a.ref,a.status));if(rows.length)out.approvals=rows}return out;}
function findItem(s){if(!selected.id)return null;return (selected.type==='activities'?s.activities:selected.type==='tasks'?s.tracking:selected.type==='emails'?(s.emails||[]):selected.type==='comments'?s.comments:s.approvals).find(x=>String(x.id)===String(selected.id));}
function item(type,r){const id=esc(r.id);if(type==='activities')return `<div class="list-item" data-type="activities" data-id="${id}"><h4>${esc(r.title)}</h4><div class="meta">${esc(r.referenceId||'—')} · ${esc(status(r))} · ${esc(r.category||'Unclassified')}</div></div>`;if(type==='tasks')return `<div class="list-item" data-type="tasks" data-id="${id}"><h4>${esc(r.title)}</h4><div class="meta">${esc(r.referenceId||'—')} · ${esc(r.assignedTo||'—')} · ${esc(r.status||'Pending')}</div></div>`;if(type==='emails')return `<div class="list-item" data-type="emails" data-id="${id}"><h4>${esc(r.subject||'No subject')}</h4><div class="meta">${esc(r.fromAddress||r.from||'—')} · ${esc(String(r.receivedDateTime||r.received||'').slice(0,16))}</div></div>`;if(type==='comments')return `<div class="list-item" data-type="comments" data-id="${id}"><h4>${esc((r.body||'').slice(0,80))}</h4><div class="meta">${esc(r.author)} · ${esc(r.referenceId||'—')}</div></div>`;return `<div class="list-item" data-type="approvals" data-id="${id}"><h4>${esc(r.title)}</h4><div class="meta">${esc(r.ref||'—')} · ${esc(r.status)}</div></div>`;}
function detail(s){const r=findItem(s);if(!r)return `<div class="empty"><h2>No item selected</h2><p>Select an item or run a direct lookup.</p></div>`;if(selected.type==='activities')return `<h2>${esc(r.title)}</h2><div class="status-strip">${badge(status(r))} ${badge(r.assignmentStatus||'Assignment pending')}</div><dl class="detail-grid"><dt>ID</dt><dd>${esc(r.id)}</dd><dt>Reference</dt><dd>${esc(r.referenceId||'—')}</dd><dt>Category</dt><dd>${esc(r.category||'—')}</dd><dt>Assigned To</dt><dd>${esc(r.assignedTo||'—')}</dd><dt>Created</dt><dd>${esc(String(r.created||'').slice(0,16))}</dd></dl><div class="form-row"><button class="btn" data-assign>Assign</button><button class="btn ghost" data-flag="dg">DG Attention</button><button class="btn ghost" data-flag="followup">Follow-Up</button><button class="btn ghost" data-flag="int">INT</button><button class="btn ghost" data-flag="unc">UNC</button></div>`;if(selected.type==='tasks')return `<h2>${esc(r.title)}</h2><div class="status-strip">${badge(r.status||'Pending')} ${badge(r.priority||'normal')}</div><dl class="detail-grid"><dt>ID</dt><dd>${esc(r.id)}</dd><dt>Reference</dt><dd>${esc(r.referenceId||'—')}</dd><dt>Owner</dt><dd>${esc(r.assignedTo||'—')}</dd><dt>Due</dt><dd>${esc(String(r.due||'—').slice(0,10))}</dd></dl><form class="grid" data-update-task><label>Progress<select name="status"><option>Not started</option><option>In progress</option><option>Completed</option><option>Deferred</option></select></label><label>Priority<select name="priority"><option>${esc(r.priority||'normal')}</option><option>P1 (High)</option><option>P2 (Medium)</option><option>P3 (Normal)</option><option>P4 (Low)</option></select></label><label class="wide">Comments<textarea name="comments" rows="3"></textarea></label><div class="wide"><button class="btn">Preview & Submit Update</button></div></form>`;if(selected.type==='emails')return `<h2>${esc(r.subject||'No subject')}</h2><dl class="detail-grid"><dt>From</dt><dd>${esc(r.fromAddress||r.from||'—')}</dd><dt>Received</dt><dd>${esc(String(r.receivedDateTime||r.received||'').slice(0,16))}</dd><dt>Attachments</dt><dd>${r.hasAttachments?'Yes':'No'}</dd></dl><div class="form-row"><button class="btn" data-email-task>Create Task</button></div><div class="email-frame"><iframe sandbox="allow-same-origin" srcdoc="${esc(r.bodyContent||r.body||r.bodyPreview||'')}"></iframe></div>`;return `<h2>${esc(r.title||r.body||'Item')}</h2><pre class="preview-box">${esc(JSON.stringify(r,null,2))}</pre>`;}
export async function mount(el){hydrateGovernance();render(el);}

function render(el){syncLocal();const s=State.get(),g=groups(s),total=Object.values(g).reduce((n,r)=>n+r.length,0);el.innerHTML=`<div class="workspace">${head('Lookup & Direct Action','Single-item lookup across documents, tasks and emails with governed flag, update and create-task actions.')}
<section class="panel lookup-direct"><div class="toolbar"><input data-q placeholder="Enter ID, reference, title or email subject" value="${esc(q)}"><select data-scope-select>${SCOPES.map(x=>`<option value="${x.value}">${x.label}</option>`).join('')}</select><button class="btn" data-direct>Direct Lookup</button><button class="btn ghost" data-back>Reset</button></div>${chips(SCOPES,scope,'data-scope')}</section>
<div class="split"><section class="panel"><div class="eyebrow">Results (${total})</div>${!q?'<p class="meta">Start typing or choose Direct Lookup for an endpoint-backed search.</p>':(!total?`<p class="meta">No local results for "${esc(q)}".</p>`:Object.entries(g).map(([type,rows])=>`<div class="result-group"><div class="eyebrow">${esc(type.toUpperCase())} (${rows.length})</div><div class="list-col">${rows.slice(0,80).map(r=>item(type,r)).join('')}</div></div>`).join(''))}</section><section class="panel">${detail(s)}</section></div></div>`;
el.querySelector('[data-scope-select]').value=scope;let timer;el.querySelector('[data-q]').oninput=e=>{const v=e.target.value,pos=e.target.selectionStart;clearTimeout(timer);timer=setTimeout(()=>{UIState.set('lookup',{q:v});render(el);const i=el.querySelector('[data-q]');i?.focus();i?.setSelectionRange(pos,pos)},120)};el.querySelector('[data-scope-select]').onchange=e=>{UIState.set('lookup',{scope:e.target.value});render(el)};el.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{UIState.set('lookup',{scope:b.dataset.scope});render(el)});el.querySelector('[data-back]').onclick=()=>{UIState.set('lookup',{q:'',selType:'',selId:''});render(el)};el.querySelector('[data-direct]').onclick=async()=>directLookup(el);el.querySelectorAll('[data-type][data-id]').forEach(c=>c.onclick=()=>{UIState.set('lookup',{selType:c.dataset.type,selId:c.dataset.id});render(el)});el.querySelector('[data-assign]')?.addEventListener('click',()=>{State.patch({selectedId:selected.id});location.hash='#/single-assignment'});el.querySelectorAll('[data-flag]').forEach(b=>b.onclick=()=>flagActivity(b.dataset.flag));el.querySelector('[data-update-task]')?.addEventListener('submit',updateTask);el.querySelector('[data-email-task]')?.addEventListener('click',createTaskFromEmail);}
async function directLookup(el){if(!q)return toast('Enter an ID, reference or title first','error');const qtype=scope==='tasks'?'FETCH_ACTIVITIES':scope==='emails'?'SUBSIDIARY_ACTIONS':'GET_DOCS';if(!await confirmAction({title:'Confirm direct lookup',body:`<p>Lookup <b>${esc(q)}</b> in ${esc(scope)}.</p><pre class="preview-box">${esc(JSON.stringify({query:q,scope},null,2))}</pre>`,confirmText:'Run lookup',cancelText:'Cancel'}))return;try{await invoke(qtype,{operation:'read',mode:'single',query:q,scope});toast('Lookup request sent; synchronize results from Operator HUD if needed','success')}catch{toast('Endpoint unavailable; local search remains active','error')}}
async function flagActivity(flag){syncLocal();const s=State.get(),a=s.activities.find(x=>String(x.id)===String(selected.id));if(!a)return;if(!await confirmAction({title:'Confirm document flag',body:`<p>${esc(a.title)}</p><p>Flag: <b>${esc(flag)}</b></p>`,confirmText:'Submit flag',cancelText:'Cancel'}))return;const now=new Date().toISOString();State.patch({activities:s.activities.map(x=>x.id===a.id?{...x,flags:[...(x.flags||[]),{flag,at:now,by:s.profile.email}]}:x)},{module:'lookup',action:'flag-document',ref:a.referenceId||String(a.id)});invoke('DYNAMIC_ACTIONS',{action:'flagDocument',flag,activityId:a.id,title:a.title}).catch(()=>toast('Flag recorded locally; sync queued','error'));toast('Flag recorded','success');}
async function updateTask(e){e.preventDefault();syncLocal();const d=Object.fromEntries(new FormData(e.target)),s=State.get(),t=s.tracking.find(x=>String(x.id)===String(selected.id));if(!t)return;const after={...t,status:d.status,priority:d.priority,comments:[...(t.comments||[]),{body:d.comments,by:s.profile.email,at:new Date().toISOString()}]};if(!await confirmAction({title:'Confirm task update',body:`<p>${esc(t.title)}</p><pre class="preview-box">${esc(JSON.stringify({before:{status:t.status,priority:t.priority},after:{status:after.status,priority:after.priority}},null,2))}</pre>`,confirmText:'Submit update',cancelText:'Cancel'}))return;State.patch({tracking:s.tracking.map(x=>String(x.id)===String(t.id)?after:x)},{module:'lookup',action:'update-task',ref:t.referenceId||''});invoke('DYNAMIC_ACTIONS',{action:'updateTask',task:after}).catch(()=>toast('Task update saved locally; sync queued','error'));toast('Task updated','success');}
async function createTaskFromEmail(){syncLocal();const s=State.get(),e=(s.emails||[]).find(x=>String(x.id)===String(selected.id));if(!e)return;const title=e.subject||'Email task',ref=makeRef(e.id||Date.now(),'EMAIL','TASK');const task={id:crypto.randomUUID(),title,status:'In progress',referenceId:ref,assignedTo:s.profile.email,priority:'P3 (Normal)',description:e.bodyPreview||'',sourceEmailId:e.id,created:new Date().toISOString()};if(!await confirmAction({title:'Create task from email',body:`<p>${esc(title)}</p><pre class="preview-box">${esc(JSON.stringify({referenceId:ref,assignedTo:task.assignedTo,priority:task.priority},null,2))}</pre>`,confirmText:'Create task',cancelText:'Cancel'}))return;State.patch({tracking:[task,...s.tracking]},{module:'lookup',action:'create-task-from-email',ref});invoke('SINGLE_ASSIGNMENT',{source:'email',email:e,tracking:task}).catch(()=>toast('Task created locally; sync queued','error'));toast('Task created from email','success');}
