import { CacheManager } from '../core/cache-manager.js';
import { LoadingState } from '../core/loading-state.js';
import { PendingQueue } from '../core/pending-queue.js';
import { capRows, RenderBudget } from '../core/render-budget.js';
import { hydrateGovernance } from '../core/governed-actions.js';
import {State} from '../core/state.js';import {head,kpis,esc,badge,toast} from '../core/ui.js';import {requestSync} from '../core/data-loader.js';
import {operationalMetrics} from '../core/metrics-service.js';
export async function mount(el){hydrateGovernance();render(el)}function render(el){const s=State.get(),load=s.runtime?.lastLoad;el.innerHTML=`<div class="workspace">${head('Operator HUD','Live operational telemetry, synchronization control and queued-action oversight.')}${kpis([['Data source',load?.key||'None'],['Queued writes',s.pending.length],['Warnings',s.runtime?.lastWarnings?.length||0],['Audit events',s.audit.length]])}<div class="dashboard-grid"><section class="panel"><h2>Synchronization</h2><p>Last load: <b>${esc(load?.at?new Date(load.at).toLocaleString():'Never')}</b></p><p>Request: <code>${esc(load?.meta?.requestId||'—')}</code></p><p>Run: <code>${esc(load?.meta?.runId||'—')}</code></p><p>Contract: ${badge(load?.meta?.contractVersion||'Unknown')}</p><button class="btn" data-sync>Synchronize now</button></section><section class="panel"><h2>Collection inventory</h2>${Object.entries(load?.counts||{}).map(([k,v])=>`<div class="action-row"><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<p>No synchronization inventory.</p>'}</section><section class="panel"><h2>Live operational metrics</h2>${(m=>['openReferences','openTasks','overdue','dueSoon','pendingApprovals','pendingDispatch'].map(k=>`<div class="action-row"><span>${esc(k.replace(/([A-Z])/g,' $1').toLowerCase())}</span><b>${m[k]}</b></div>`).join(''))(operationalMetrics(s))}</section><section class="panel"><h2>Data operations</h2>${(d=>`<div class="action-row"><span>cache entries</span><b>${esc(String(d.cache?.entries??d.cache?.size??'—'))}</b></div><div class="action-row"><span>loading states</span><b>${esc(String(Object.keys(d.loading||{}).length))}</b></div><div class="action-row"><span>pending writes</span><b>${esc(String(d.pending?.count??s.pending.length))}</b></div>`)(operatorDataOpsSummary())}</section><section class="panel wide-panel"><h2>Pending write queue</h2>${capRows(s.pending,RenderBudget.pendingRows).map(p=>`<div class="action-row"><span><b>${esc(p.key)}</b><small>${esc(p.at)} · ${esc(p.error)}</small></span>${badge('Queued')}</div>`).join('')||'<p>No queued writes.</p>'}</section></div></div>`;el.querySelector('[data-sync]').onclick=async e=>{e.target.disabled=true;try{await requestSync({source:'operator-hud',mode:'full'});toast('Synchronization completed','success');render(el)}catch(x){toast(x.message,'error')}finally{e.target.disabled=false}}}

export function operatorDataOpsSummary(){ return {cache:CacheManager.stats(), loading:LoadingState.snapshot(), pending:PendingQueue.stats()}; }
