export const ActionOwnership = Object.freeze({
  'create-correspondence': { owner:'correspondence', service:'Entities.create', audit:'audit:correspondence-created', backend:'DYNAMIC_ACTIONS.optional' },
  triage: { owner:'correspondence', service:'Entities.transitionStatus', audit:'audit:triage-completed', backend:'DYNAMIC_ACTIONS.optional' },
  'assign-one': { owner:'single-assignment', service:'Entities.create(task)', audit:'audit:assigned', backend:'SINGLE_ASSIGNMENT' },
  'bulk-assign': { owner:'bulk-assignment', service:'OtpService+Idempotency', audit:'audit:bulk-assignment-submitted', backend:'BULK_ASSIGNMENT' },
  acknowledge: { owner:'acknowledgment', service:'governedTransition', audit:'audit:acknowledged', backend:'DYNAMIC_ACTIONS.optional' },
  'start-work': { owner:'orchestrator', service:'governedTransition', audit:'audit:work-started', backend:'DYNAMIC_ACTIONS.optional' },
  'complete-action': { owner:'orchestrator', service:'governedTransition', audit:'audit:action-complete', backend:'DYNAMIC_ACTIONS.optional' },
  approve: { owner:'approvals', service:'governedTransition', audit:'audit:approved', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-approve': { owner:'executive', service:'governedTransition', audit:'audit:executive-approved', backend:'DYNAMIC_ACTIONS.optional' },
  'send-dispatch': { owner:'dispatch', service:'DispatchService.dispatchOutbound', audit:'audit:dispatch-started', backend:'DISPATCH_OUTBOUND' },
  'archive-reference': { owner:'archive', service:'ArchiveService.archiveReference', audit:'audit:archived', backend:'ARCHIVE_REFERENCE.optional' },
  'generate-report': { owner:'reports', service:'ReportExportService', audit:'audit:report-generated', backend:'none' },
  'run-checks': { owner:'diagnostics', service:'Diagnostics', audit:'audit:diagnostics-run', backend:'none' },
  'profile': { owner:'settings', service:'State.patch', audit:'audit:settings-updated', backend:'none' },
  'create-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-created', backend:'DYNAMIC_ACTIONS.optional' },
  'update-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'disable-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-disabled', backend:'DYNAMIC_ACTIONS.optional' },
  'create-approval': { owner:'approvals', service:'State.patch', audit:'audit:approval-requested', backend:'DYNAMIC_ACTIONS.optional' },
  reject: { owner:'approvals', service:'governedTransition', audit:'audit:rejected', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-return': { owner:'executive', service:'governedTransition', audit:'audit:executive-returned', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-escalate': { owner:'executive', service:'governedTransition', audit:'audit:executive-escalated', backend:'DYNAMIC_ACTIONS.optional' },
  'append-minute': { owner:'executive', service:'State.patch', audit:'audit:executive-minute', backend:'DYNAMIC_ACTIONS.optional' },
  'route-task': { owner:'executive', service:'createTask', audit:'audit:task-routed', backend:'SINGLE_ASSIGNMENT' },
  'add-comment': { owner:'comments', service:'State.patch', audit:'audit:comment-added', backend:'DYNAMIC_ACTIONS.optional' },
  'remind-assignee': { owner:'acknowledgment', service:'State.patch', audit:'audit:ack-reminder', backend:'DYNAMIC_ACTIONS.optional' },
  'register-file': { owner:'registry', service:'createRegistryFile', audit:'audit:file-registered', backend:'DYNAMIC_ACTIONS.optional' },
  'route-file': { owner:'registry', service:'createMovement', audit:'audit:file-routed', backend:'DYNAMIC_ACTIONS.optional' },
  'receive-file': { owner:'registry', service:'State.patch', audit:'audit:custody-received', backend:'DYNAMIC_ACTIONS.optional' },
  'close-file': { owner:'registry', service:'State.patch', audit:'audit:file-closed', backend:'DYNAMIC_ACTIONS.optional' },
  'archive-file': { owner:'registry', service:'ArchiveService.archiveReference', audit:'audit:file-archived', backend:'ARCHIVE_REFERENCE.optional' },
  'update-operation': { owner:'activities', service:'updateTaskState', audit:'audit:operation-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'set-reminder': { owner:'orchestrator', service:'State.patch', audit:'audit:reminder-set', backend:'DYNAMIC_ACTIONS' },
  'no-dispatch': { owner:'dispatch', service:'State.patch', audit:'audit:no-dispatch', backend:'none' },
  'retry-dispatch': { owner:'dispatch', service:'WriteManager.backend', audit:'audit:dispatch-retried', backend:'DYNAMIC_ACTIONS' },
  'close-dispatch': { owner:'dispatch', service:'State.patch', audit:'audit:dispatch-closed', backend:'DYNAMIC_ACTIONS.optional' },
  'flag-document': { owner:'lookup', service:'State.patch', audit:'audit:document-flagged', backend:'DYNAMIC_ACTIONS.optional' },
  'update-task': { owner:'lookup', service:'updateTaskState', audit:'audit:task-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'create-task-from-email': { owner:'lookup', service:'createTask', audit:'audit:email-task-created', backend:'SINGLE_ASSIGNMENT' },
  'convert-email': { owner:'correspondence', service:'Entities.create', audit:'audit:email-converted', backend:'DYNAMIC_ACTIONS.optional' },
  'request-otp': { owner:'bulk-assignment', service:'OtpService.requestOtp', audit:'audit:otp-requested', backend:'OTP_GENERATE' },
  'verify-otp': { owner:'bulk-assignment', service:'OtpService.verifyOtp', audit:'audit:otp-verified', backend:'OTP_VERIFY' },
  'resolve-escalation': { owner:'fasttrack', service:'State.patch', audit:'audit:escalation-resolved', backend:'DYNAMIC_ACTIONS.optional' },
  'import-state': { owner:'settings', service:'DataReconciler.apply', audit:'audit:state-imported', backend:'none' }
});
export function actionSpec(action){ return ActionOwnership[action] || null; }
export function actionOwner(action){ return actionSpec(action)?.owner || ''; }
