import { Entities } from './entity-store.js';
import { AuditLog } from './audit-log.js';
import { Retention } from './retention.js';
import { ExportBundle } from './export-bundle.js';
import { createClosureError, createScopeError, createValidationError } from './errors.js';
export const ArchiveService=Object.freeze({canArchive,buildBundle,archiveReference,accessArchive,reopenArchive,exportArchive});
export async function canArchive(ref){ const c=Entities.canClose(ref); return c.ok?{ok:true,ref,closeState:c}:{ok:false,reason:'CLOSURE_GATE_FAILED',details:c}; }
export async function buildBundle(ref,actor,meta={}){ const can=await canArchive(ref); if(!can.ok) throw createClosureError('Archive blocked by closure gate.',can); const records=Entities.byReference(ref,{actor}); const auditThread=AuditLog.byReference(ref); const retention=Retention.calculate(records,meta); const bundle={ref,archivedAt:new Date().toISOString(),archivedBy:actor,immutable:true,version:1,...retention,closureSummary:meta.closureSummary||'',records,auditThread,derivedFrom:null}; bundle.hash=await ExportBundle.createArchiveHash(bundle); return Object.freeze(structuredClone(bundle)); }
export async function archiveReference(ref,actor,meta={}){ const bundle=await buildBundle(ref,actor,meta); const archived=Entities.archive(ref,actor,{bundle,retentionUntil:bundle.retentionUntil,hash:bundle.hash}); AuditLog.record({ref,actor,event:'audit:archived',phase:6,meta:{hash:bundle.hash,retentionUntil:bundle.retentionUntil}}); return archived; }
export function accessArchive(ref,actor){ const archive=Entities.getArchive(ref); if(!archive) throw createValidationError('Archive not found.',{ref}); if(!canAccessArchive(archive,actor)){ AuditLog.record({ref,actor,event:'audit:unauthorized-access-attempt',phase:6,meta:{operation:'archive-access'}}); throw createScopeError('Archive access denied.',{ref}); } AuditLog.record({ref,actor,event:'audit:archive-accessed',phase:6}); return archive; }
function canAccessArchive(archive,actor={}){ if(['admin','executive','registry','audit'].includes(actor.persona)) return true; const scope=actor.directorateScope||[]; if(scope.includes('all')) return true; return Object.values(archive.records||{}).flat().some(r=>scope.includes(r.__directorate)); }
export function reopenArchive(ref,actor,reason){ if(!['admin','executive','registry'].includes(actor.persona)) throw createScopeError('Only authorized personas may reopen archives.',{ref}); if(!reason) throw createValidationError('Reopen reason is required.',{ref}); const archive=accessArchive(ref,actor); const newRef=Entities.createReference({derivedFrom:ref,linkedRefs:[ref],reason,sourceArchiveHash:archive.hash,__status:'arrival'}); AuditLog.record({ref,actor,event:'audit:reopened-as-new-ref',phase:6,meta:{newRef:newRef.__ref,reason,sourceArchiveHash:archive.hash}}); AuditLog.record({ref:newRef.__ref,actor,event:'audit:created-from-archive',phase:1,meta:{derivedFrom:ref}}); return newRef; }
export async function exportArchive(ref,actor){ const archive=accessArchive(ref,actor); return {manifest:await ExportBundle.createArchiveManifest(archive,actor.email),archiveJson:ExportBundle.createArchiveJson(archive),evidenceIndex:ExportBundle.createEvidenceIndex(archive)}; }
