import { Entities } from './entity-store.js';
import { AuditLog } from './audit-log.js';
import { Idempotency } from './idempotency.js';
import { invokeObsidianAction } from './security-actions.js';
import { createValidationError, createError, ErrorClass } from './errors.js';
export const DispatchService=Object.freeze({prepareDispatch,dispatchOutbound,markDispatchFailed,markNoDispatch,getReceipt,canDispatch});
export function canDispatch(ref){ const b=Entities.byReference(ref,{profile:{persona:'admin'}}); const approvals=b.approval||[]; return approvals.length===0 || approvals.some(a=>['approved','approved_with_edit'].includes(a.__status)); }
export function prepareDispatch({ref,actor,channel='email',recipients=[],approvedResponse={},attachments=[]}){ if(!canDispatch(ref)) throw createValidationError('Dispatch requires an approved response.',{ref}); return Entities.createDispatch({__ref:ref,actor,channel,recipients,approvedResponse,attachments,__status:'dispatch_pending'}); }
export async function dispatchOutbound({ref,actor,channel='email',recipients=[],approvedResponse={},attachments=[],meta={}}){ if(!recipients.length) throw createValidationError('Dispatch requires at least one recipient.',{ref}); const payload={channel,recipients,approvedResponse,attachments}; const idempotencyKey=await Idempotency.key({operation:'DISPATCH_OUTBOUND',ref,actor,payload,windowSeconds:600}); const dispatch=prepareDispatch({ref,actor,...payload}); try{ await Entities.transitionStatus(ref,'dispatch_pending','dispatch_in_flight',actor,{dispatchId:dispatch.__id,idempotencyKey}); }catch{} AuditLog.record({ref,actor,event:'audit:dispatch-started',phase:5,meta:{idempotencyKey,channel,recipientsCount:recipients.length}}); const res=await invokeObsidianAction('DISPATCH_OUTBOUND',{ref,actor,...payload,idempotencyKey,meta}); if(res?.ok===false) return markDispatchFailed(ref,actor,res); try{ await Entities.transitionStatus(ref,'dispatch_in_flight','dispatched',actor,{receipt:res.receipt||res}); }catch{} AuditLog.record({ref,actor,event:'audit:dispatch-receipt-captured',phase:5,meta:{receipt:res.receipt||res}}); return res; }
export function markDispatchFailed(ref,actor,error={}){ AuditLog.record({ref,actor,event:'audit:dispatch-failed',phase:5,meta:error}); throw createError(ErrorClass.DISPATCH_FAILED,error.message||'Dispatch failed.',error); }
export async function markNoDispatch(ref,actor,reason){ if(!reason) throw createValidationError('No-dispatch reason is required.',{ref}); try{ await Entities.transitionStatus(ref,'dispatch_pending','no_dispatch',actor,{reason}); await Entities.transitionStatus(ref,'no_dispatch','closure_check',actor,{reason}); }catch{} return Entities.byReference(ref,{actor}); }
export function getReceipt(ref){ const b=Entities.byReference(ref,{profile:{persona:'admin'}}); return (b.dispatch||[]).map(d=>d.receipt).filter(Boolean); }
