const now=()=>new Date().toISOString();
const uid=p=>`${p}-${crypto.randomUUID()}`;
const val=(...x)=>x.find(v=>v!==undefined&&v!==null&&v!=='')??'';
export const CorrespondenceStates=Object.freeze(['Received','Logged','Reviewed','Classified','Assigned','In Treatment','Completed','Closed','Archived','On Hold','Rejected','Duplicate']);
export const OperationStates=Object.freeze(['Not Started','In Progress','Awaiting Response','Pending Approval','Escalated','Blocked','Completed','Closed']);
export const RegistryStates=Object.freeze(['Unregistered','Registered','In Registry','Routed','Received','Awaiting Collection','Dispatched','Closed','Archived']);
export function enrichCorrespondence(a,old={}){const treated=['Treated','Processed'].includes(a.status);return{...old,id:String(a.id),sourceId:a.sourceId,referenceId:a.referenceId||old.referenceId||'',subject:a.title,sender:old.sender||'',senderEmail:old.senderEmail||'',receivedAt:a.created,correspondenceType:old.correspondenceType||'Incoming',channel:old.channel||'Document',category:a.category||old.category||'',subcategory:old.subcategory||'',assignedTo:a.assignedTo||old.assignedTo||'',assignedDsu:old.assignedDsu||'',status:old.status||(treated?'In Treatment':'Received'),priority:old.priority||'Normal',confidentiality:old.confidentiality||'Official',attachmentLink:a.attachmentLink||'',description:a.description||'',duplicateOf:old.duplicateOf||'',holdReason:old.holdReason||'',closedAt:old.closedAt||'',createdAt:old.createdAt||a.created,updatedAt:now()}}
export function enrichOperation(t,old={}){return{...old,id:String(t.id),sourceId:t.sourceId,referenceId:t.referenceId||'',title:t.title,description:t.description||'',owner:t.assignedTo||'',dsu:t.assignedToDsu||'',supportingDsu:t.supportingDsu||'',status:old.status||mapTaskStatus(t.status),priority:t.priority||'normal',startDate:t.startDate||t.created,dueDate:t.due||'',progress:Number(old.progress??parseProgress(t.progress)),blockedReason:old.blockedReason||'',dependencies:old.dependencies||[],milestones:old.milestones||[],escalationLevel:Number(old.escalationLevel||0),createdAt:old.createdAt||t.created,updatedAt:now()}}
function mapTaskStatus(s){const x=String(s||'').toLowerCase();if(x.includes('complete'))return'Completed';if(x.includes('progress'))return'In Progress';if(x.includes('await'))return'Awaiting Response';return'Not Started'}
function parseProgress(x){const n=parseInt(x,10);return Number.isFinite(n)?Math.min(100,Math.max(0,n)):0}
export function registryNumber(sourceId,date=new Date()){const y=new Date(date).getFullYear()||new Date().getFullYear();return `DGO/${y}/${String(sourceId||Date.now()).padStart(6,'0')}`}
export function reconcileEnterprise(state){const corrMap=new Map((state.correspondence||[]).map(x=>[String(x.id),x])),opsMap=new Map((state.operations||[]).map(x=>[String(x.id),x]));const correspondence=(state.activities||[]).map(a=>enrichCorrespondence(a,corrMap.get(String(a.id))));const operations=(state.tracking||[]).map(t=>enrichOperation(t,opsMap.get(String(t.id))));return{correspondence,operations}}
export function createMovement(file,{from,to,action='FOR_ACTION',priority='MEDIUM',minute='',by='',status='Routed'}){return{id:uid('MOV'),registryFileId:file.id,registryNumber:file.registryNumber,referenceId:file.referenceId,from:from||file.currentHolder||'Central Registry',to,action,priority,minute,status,releasedAt:now(),receivedAt:'',receivedBy:'',createdBy:by,createdAt:now()}}
export function createRegistryFile(corr,by){return{id:uid('REG'),correspondenceId:corr.id,referenceId:corr.referenceId||'',registryNumber:registryNumber(corr.sourceId||corr.id,corr.receivedAt),subject:corr.subject,sender:corr.sender,status:'Registered',currentHolder:'Central Registry',currentDsu:'Registry',registeredAt:now(),registeredBy:by,closedAt:'',archivedAt:'',retentionClass:'Official correspondence',securityClass:corr.confidentiality||'Official'}}
export function audit(action,entityType,entityId,details={},actor=''){return{id:uid('AUD'),at:now(),action,entityType,entityId,actor,details}}
