import { deriveDirectorate, canReadRecord } from './directorate-scope.js';
import { AuditLog } from './audit-log.js';
import { assertTransitionAllowed, validateGate } from './lifecycle.js';
import { createValidationError, createClosureError } from './errors.js';
const _store=new Map(), _byRef=new Map(), _archive=new Map(), _quarantine=new Map(), _dedupIndex=new Map(), _raw=new Map();
const HYDRATION_MAP={activities:'document',correspondence:'correspondence',tracking:'task',operations:'operation',comments:'comment',approvals:'approval',dispatches:'dispatch',registryFiles:'registryFile',fileMovements:'movement',registryMinutes:'minute',emails:'email',escalations:'escalation',notifications:'notification'};
const CHILD_TYPES=new Set(['task','operation','comment','approval','dispatch','movement','minute','auditEvent']);
const TERMINAL={task:['action_complete','closed','cancelled','Completed','Closed'],operation:['action_complete','closed','cancelled','Completed','Closed'],approval:['approved','approved_with_edit','rejected','escalated'],dispatch:['dispatched','no_dispatch','closed'],comment:['closed','archived']};
const uid=p=>`${p}-${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}`; const clone=v=>structuredClone(v); const freeze=v=>Object.freeze(clone(v));
function clear(){_store.clear();_byRef.clear();_archive.clear();_quarantine.clear();_dedupIndex.clear();_raw.clear();}
function refOf(r){return String(r.__ref||r.referenceId||r.reference||r.RefIDD||r.Reference_ID||r.ref||r.registryNumber||r.id||r.ID||'').trim();}
function statusOf(r,type){return String(r.__status||r.status||r.Status||r.progress||(type==='dispatch'?'dispatch_pending':'arrival')).trim();}
function phaseOf(status){ if(['arrival','registered','triaged','triage_complete','duplicate','rejected','on_hold','Received','Logged','Reviewed','Classified'].includes(status)) return 1; if(['assigning','assigned','assignment_failed','Assigned'].includes(status)) return 2; if(['acknowledged','in_progress','blocked','awaiting_response','action_complete','In Progress','In Treatment','Completed'].includes(status)) return 3; if(['pending_review','approved','approved_with_edit','returned','escalated','rejected'].includes(status)) return 4; if(['dispatch_pending','dispatch_in_flight','dispatched','dispatch_failed','no_dispatch','closure_check','closed','Dispatched','Closed'].includes(status)) return 5; if(['archived','reopen_requested','reopened_as_new_ref','Archived'].includes(status)) return 6; return 1; }
function normalize(type,row,state={}){ let ref=refOf(row); if(CHILD_TYPES.has(type) && !(row.__ref||row.referenceId||row.reference||row.RefIDD||row.Reference_ID||row.ref||row.registryNumber)) ref=''; const st=statusOf(row,type); const rec={...row,__id:String(row.__id||row.id||row.ID||uid(type.toUpperCase())),__type:type,__ref:ref,__directorate:'',__phase:row.__phase||phaseOf(st),__status:st,__source:row.__source||'STATE',__sourceId:String(row.sourceId||row.ID||row.id||''),__createdAt:row.__createdAt||row.created||row.Created||new Date().toISOString(),__updatedAt:new Date().toISOString(),__version:row.__version||1}; rec.__directorate=deriveDirectorate(rec,state)||'UNSCOPED'; return rec; }
function insert(rec){ if(CHILD_TYPES.has(rec.__type) && !rec.__ref) return quarantine(rec,'missing-reference'); const t=rec.__type; if(!_store.has(t)) _store.set(t,new Map()); _store.get(t).set(rec.__id,rec); if(rec.__ref){ const b=_byRef.get(rec.__ref)||{}; (b[t] ||= []).push(rec); _byRef.set(rec.__ref,b); } return rec; }
export const Entities=Object.freeze({hydrateFromState,all,get,byReference,create,createReference,createDispatch,transitionStatus,canClose,archive,getArchive,writeArchive,markArchived,quarantine,lookupQuarantine,dedup,snapshot,restoreSnapshot,stats});
export function hydrateFromState(state={}){ clear(); for(const [col,type] of Object.entries(HYDRATION_MAP)){ for(const row of (state[col]||[])){ _raw.set(`${col}:${row.id||row.ID||uid('RAW')}`, row); insert(normalize(type,row,state)); } } AuditLog.hydrateFromState?.(state); return snapshot(); }
export function all(type,options={}){ const profile=options.profile||options.actor||{}; const rows=Array.from((_store.get(type)||new Map()).values()).filter(r=>canReadRecord(r,profile)); return freeze(rows); }
export function get(type,id,options={}){ const rec=(_store.get(type)||new Map()).get(String(id)); if(!rec||!canReadRecord(rec,options.profile||options.actor||{})) return null; return freeze(rec); }
export function byReference(ref,options={}){ const profile=options.profile||options.actor||{}; const b=_byRef.get(ref)||{}; const out={}; for(const [t,rows] of Object.entries(b)) out[t]=rows.filter(r=>canReadRecord(r,profile)); return freeze(out); }
export function create(type,row,state={}){ return freeze(insert(normalize(type,row,state))); }
export function createReference(row={}){ const ref=row.__ref||row.ref||`REF-${new Date().getFullYear()}-${Date.now()}`; return create('reference',{...row,__ref:ref,__status:row.__status||'arrival'}); }
export function createDispatch(row={}){ return create('dispatch',{...row,__status:row.__status||'dispatch_pending',__phase:5}); }
export async function transitionStatus(ref,fromStatus,toStatus,actor={},meta={}){ const bundle=_byRef.get(ref); if(!bundle) throw createValidationError('Reference not found',{ref}); const primary=(bundle.correspondence||bundle.document||bundle.reference||bundle.task||[])[0]; const current=fromStatus||primary?.__status||'arrival'; assertTransitionAllowed(current,toStatus); validateGate(toStatus,bundle,meta,{canClose:()=>canClose(ref)}); Object.values(bundle).flat().forEach(r=>{ if(r.__ref===ref){ r.__status=toStatus; r.__phase=phaseOf(toStatus); r.__updatedAt=new Date().toISOString(); }}); AuditLog.record({ref,actor,event:'audit:phase-transition',phase:phaseOf(toStatus),fromStatus:current,toStatus,meta}); return byReference(ref,{actor}); }
export function canClose(ref){ const b=_byRef.get(ref)||{}; const openTasks=[...(b.task||[]),...(b.operation||[])].filter(x=>!(TERMINAL.task.includes(x.__status)||TERMINAL.operation.includes(x.__status))); const openApprovals=(b.approval||[]).filter(x=>!TERMINAL.approval.includes(x.__status)); const openDispatches=(b.dispatch||[]).filter(x=>!TERMINAL.dispatch.includes(x.__status)|| (x.__status==='no_dispatch'&&!x.noDispatchReason)); return freeze({ok:!openTasks.length&&!openApprovals.length&&!openDispatches.length,openTasks,openApprovals,openDispatches}); }
export function archive(ref,actor={},meta={}){ const c=canClose(ref); if(!c.ok) throw createClosureError('Closure gate failed.', c); const bundle=meta.bundle||{ref,archivedAt:new Date().toISOString(),archivedBy:actor,immutable:true,records:byReference(ref,{actor}),auditThread:AuditLog.byReference(ref),retentionUntil:meta.retentionUntil||'',hash:meta.hash||''}; writeArchive(ref,bundle); markArchived(ref); AuditLog.record({ref,actor,event:'audit:archived',phase:6,meta:{hash:bundle.hash||''}}); return getArchive(ref); }
export function writeArchive(ref,bundle){ if(!bundle?.ref||!bundle.records||!Array.isArray(bundle.auditThread)) throw createValidationError('Invalid archive bundle',{ref}); _archive.set(ref,deepFreeze(clone(bundle))); return getArchive(ref); }
export function markArchived(ref){ const b=_byRef.get(ref)||{}; Object.values(b).flat().forEach(r=>{r.__status='archived';r.__phase=6;}); }
export function getArchive(ref){ const a=_archive.get(ref); return a?freeze(a):null; }
export function quarantine(raw,reason){ const q={id:uid('Q'),at:new Date().toISOString(),reason,raw,reviewed:false}; _quarantine.set(q.id,q); AuditLog.record({ref:raw.__ref||raw.referenceId||'',event:'audit:quarantined',meta:{reason}}); return null; }
export function lookupQuarantine(){ return freeze(Array.from(_quarantine.values())); }
export function dedup(record){ const key=[record.subject||record.title,record.sender||record.senderEmail,record.attachmentLink,record.__ref].join('|').toLowerCase(); const duplicateOf=_dedupIndex.get(key); if(duplicateOf) return freeze({duplicate:true,duplicateOf,confidence:.94,reasons:['same-key']}); _dedupIndex.set(key,record.__ref); return freeze({duplicate:false}); }
export function snapshot(){ return freeze({store:Array.from(_store.entries()).map(([k,v])=>[k,Array.from(v.values())]),byRef:Array.from(_byRef.entries()),archive:Array.from(_archive.entries()),quarantine:Array.from(_quarantine.values())}); }
export function restoreSnapshot(s){ clear(); for(const [t,rows] of (s.store||[])) for(const r of rows) insert(r); for(const [r,b] of (s.archive||[])) _archive.set(r,b); }
export function stats(){ return freeze({types:Object.fromEntries(Array.from(_store.entries()).map(([k,v])=>[k,v.size])),references:_byRef.size,archives:_archive.size,quarantine:_quarantine.size}); }
function deepFreeze(v){ if(v&&typeof v==='object'){ Object.freeze(v); Object.values(v).forEach(deepFreeze); } return v; }
